### PR TITLE
Add a way to deploy kubic withou a CNI (--pod-network=none)

### PR DESCRIPTION
**Pull request by 0pendev**
A few times I wanted to use kubic for it's CRI-O and etcd integration with a CNI that was not flannel, cilium, weavenet or an upstream version of these CNI.

I did not wanted to make a request for a feature so I tried to add it myself. It was tested on single and multi-master setups.

On my first commit I had a few junk modifications done by an automatic gofmt. I ran it on all the code (it's on a separate commit so it can be undone easily).

I also updated the README to mention the posibility.

### CODE REVIEW

**Comment by thkukuk** [comment]
It would have been better if you would have separated the real change and the formating, all the format changes make it pretty hard to find and review your real code changes. 
But looks Ok to me, if I haven't missed a change.

Could you please remove the "WIP" from the commit message?

**Comment by 0pendev** [comment]
> It would have been better if you would have separated the real change and the formating, all the format changes make it pretty hard to find and review your real code changes.

The real code change is only on the first commit that was marked as WIP.

> But looks Ok to me, if I haven't missed a change.
> 
> Could you please remove the "WIP" from the commit message?

I've removed the WIP from the commit message. 

Are you fine with the addition in the README ?

**Comment by 0pendev** [comment]
Hi @thkukuk 

Does it need another modification ?

**Comment by thkukuk** [comment]
Sorry, was busy with other things.
The "à" in the README.md looks wrong to me. Else it looks ok.

**Comment by 0pendev** [comment]
> Sorry, was busy with other things.
> The "à" in the README.md looks wrong to me. Else it looks ok.

I fixed the typo in the README

**Pull request merged**
